spring:
  application:
    name: userManager

  datasource:
    url: jdbc:postgresql://localhost:5432/userManager
    username: ""
    password: ""
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
