spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userManager
    username: "postgres"
    password: "root"
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: root
      password: root

